# Generated by Django 5.2.6 on 2026-02-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("content", models.TextField()),
                (
                    "mood",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("happy", "Happy"),
                            ("thinking", "Thinking"),
                            ("inspired", "Inspired"),
                            ("tired", "Tired"),
                            ("calm", "Calm"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Journal entries",
                "ordering": ["-created_at"],
            },
        ),
    ]
