# Generated by Django 6.0.2 on 2026-02-24 08:57

import django.db.models.deletion
import home_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='Sakanasa', max_length=100)),
                ('role', models.CharField(default='Full-Stack Developer', max_length=100)),
                ('bio', models.TextField(blank=True, default='熱愛用程式解決問題的開發者...')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=home_page.models.avatar_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.PositiveSmallIntegerField(default=70)),
                ('gradient', models.CharField(choices=[('lavender-blue', 'Lavender → Blue'), ('pink-lavender', 'Pink → Lavender'), ('blue-pink', 'Blue → Pink'), ('lavender-pink', 'Lavender → Pink')], default='lavender-blue', max_length=30)),
                ('label_color', models.CharField(choices=[('cyrene-lavender', 'Lavender'), ('cyrene-pink', 'Pink'), ('cyrene-blue', 'Blue')], default='cyrene-lavender', max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='home_page.profile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
