# Generated by Django 3.2.6 on 2025-05-22 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeckCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('participants', models.PositiveIntegerField()),
                ('pie_chart', models.ImageField(blank=True, null=True, upload_to='pie_charts/')),
                ('decks', models.ManyToManyField(related_name='games', to='pie_chart.DeckCode')),
            ],
        ),
        migrations.AddField(
            model_name='deckcode',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deck_codes', to='pie_chart.series'),
        ),
    ]
